on:
  push:
     branches:
       - main

name: deploy_website

jobs:
  blogdown:
    name: render-site
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("devtools","rmarkdown","pkgdown","tidyverse","rpmodel"))'
      - name: Install sofunCalVal
        run: Rscript -e 'devtools::install_github("computationales/sofunCalVal")'
      - name: Render site
        run: Rscript -e 'pkgdown::build_site()'
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/settings/tokens

# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: blogdown
   steps:
     - name: Checkout
       uses: actions/checkout@main
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: docs # optional
         # Destination path
         path: docs # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@master
       with:
        # build dir
        build_dir: docs/
        #cname: NA
        email: koen.hufkens@gmail.com
        jekyll: no
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/settings/tokens
